import type { IconType } from "react-icons"
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiVuedotjs,
  SiNuxtdotjs,
  SiAngular,
  SiSvelte,
  SiTailwindcss,
  SiCss3,
  SiSass,
  SiHtml5,
  SiGreensock,
  SiThreedotjs,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiFastapi,
  SiDjango,
  SiFlask,
  SiGo,
  SiRust,
  SiGraphql,
  SiApollographql,
  SiAmazonwebservices,
  SiGooglecloud,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiGithubactions,
  SiGitlab,
  SiJenkins,
  SiGrafana,
  SiPrometheus,
  SiDatadog,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiMongodb,
  SiElasticsearch,
  SiSqlite,
  SiSupabase,
  SiFirebase,
  SiGit,
  SiLinux,
  SiVim,
  SiNeovim,
  SiFigma,
  SiWebpack,
  SiVite,
  SiJest,
  SiCypress,
  SiStorybook,
  SiVercel,
  SiNetlify,
  SiNginx,
  SiApache,
  SiRabbitmq,
  SiApachekafka,
  SiStripe,
  SiAuth0,
  SiJsonwebtokens,
  SiSwagger,
  SiPostman,
  SiGnubash,
  SiPrisma,
  SiDrizzle,
  SiZod,
  SiVitest,
  SiTestinglibrary,
  SiSentry,
  SiCloudflare,
  SiDigitalocean,
  SiHeroku,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiBun,
  SiDeno,
  SiElectron,
  SiReactquery,
  SiRedux,
  SiFramer,
  SiMarkdown,
  SiNotion,
  SiJira,
  SiSlack,
  SiOpenai,
  SiRuby,
  SiRubyonrails,
  SiPhp,
  SiLaravel,
  SiSharp,
  SiDotnet,
  SiOpenjdk,
  SiSpring,
  SiKotlin,
  SiSwift,
  SiFlutter,
  SiDart,
  SiReactos,
  SiSolidity,
  SiWebassembly,
  SiTauri,
  SiAstro,
  SiRemix,
  SiGatsby,
} from "react-icons/si"
import { TbApi, TbBrandAzure, TbShieldLock, TbServer, TbTestPipe2 } from "react-icons/tb"

export interface TechIcon {
  icon: IconType
  color: string
}

/**
 * Maps icon_name (from DB) → { icon component, brand color }.
 * Brand colors are used for hover effects on skill cards.
 * Add new entries here when new skills are created.
 */
export const techIcons: Record<string, TechIcon> = {
  // Frontend
  react: { icon: SiReact, color: "#61DAFB" },
  nextjs: { icon: SiNextdotjs, color: "#ffffff" },
  typescript: { icon: SiTypescript, color: "#3178C6" },
  javascript: { icon: SiJavascript, color: "#F7DF1E" },
  vuejs: { icon: SiVuedotjs, color: "#4FC08D" },
  nuxtjs: { icon: SiNuxtdotjs, color: "#00DC82" },
  angular: { icon: SiAngular, color: "#DD0031" },
  svelte: { icon: SiSvelte, color: "#FF3E00" },
  tailwindcss: { icon: SiTailwindcss, color: "#06B6D4" },
  css: { icon: SiCss3, color: "#1572B6" },
  sass: { icon: SiSass, color: "#CC6699" },
  html: { icon: SiHtml5, color: "#E34F26" },
  gsap: { icon: SiGreensock, color: "#88CE02" },
  threejs: { icon: SiThreedotjs, color: "#ffffff" },
  framer: { icon: SiFramer, color: "#0055FF" },
  astro: { icon: SiAstro, color: "#FF5D01" },
  remix: { icon: SiRemix, color: "#ffffff" },
  gatsby: { icon: SiGatsby, color: "#663399" },
  webassembly: { icon: SiWebassembly, color: "#654FF0" },

  // Backend
  nodejs: { icon: SiNodedotjs, color: "#339933" },
  express: { icon: SiExpress, color: "#ffffff" },
  python: { icon: SiPython, color: "#3776AB" },
  fastapi: { icon: SiFastapi, color: "#009688" },
  django: { icon: SiDjango, color: "#092E20" },
  flask: { icon: SiFlask, color: "#ffffff" },
  go: { icon: SiGo, color: "#00ADD8" },
  rust: { icon: SiRust, color: "#ffffff" },
  graphql: { icon: SiGraphql, color: "#E10098" },
  apollo: { icon: SiApollographql, color: "#311C87" },
  ruby: { icon: SiRuby, color: "#CC342D" },
  rails: { icon: SiRubyonrails, color: "#CC0000" },
  php: { icon: SiPhp, color: "#777BB4" },
  laravel: { icon: SiLaravel, color: "#FF2D20" },
  csharp: { icon: SiSharp, color: "#239120" },
  dotnet: { icon: SiDotnet, color: "#512BD4" },
  java: { icon: SiOpenjdk, color: "#007396" },
  spring: { icon: SiSpring, color: "#6DB33F" },
  kotlin: { icon: SiKotlin, color: "#7F52FF" },
  swift: { icon: SiSwift, color: "#FA7343" },
  deno: { icon: SiDeno, color: "#ffffff" },
  bun: { icon: SiBun, color: "#fbf0df" },
  api: { icon: TbApi, color: "#6366f1" },
  microservices: { icon: TbServer, color: "#8b5cf6" },

  // DevOps & Cloud
  aws: { icon: SiAmazonwebservices, color: "#FF9900" },
  gcp: { icon: SiGooglecloud, color: "#4285F4" },
  azure: { icon: TbBrandAzure, color: "#0078D4" },
  docker: { icon: SiDocker, color: "#2496ED" },
  kubernetes: { icon: SiKubernetes, color: "#326CE5" },
  terraform: { icon: SiTerraform, color: "#7B42BC" },
  githubactions: { icon: SiGithubactions, color: "#2088FF" },
  gitlab: { icon: SiGitlab, color: "#FC6D26" },
  jenkins: { icon: SiJenkins, color: "#D24939" },
  grafana: { icon: SiGrafana, color: "#F46800" },
  prometheus: { icon: SiPrometheus, color: "#E6522C" },
  datadog: { icon: SiDatadog, color: "#632CA6" },
  vercel: { icon: SiVercel, color: "#ffffff" },
  netlify: { icon: SiNetlify, color: "#00C7B7" },
  cloudflare: { icon: SiCloudflare, color: "#F38020" },
  digitalocean: { icon: SiDigitalocean, color: "#0080FF" },
  heroku: { icon: SiHeroku, color: "#430098" },
  nginx: { icon: SiNginx, color: "#009639" },
  apache: { icon: SiApache, color: "#D22128" },
  security: { icon: TbShieldLock, color: "#10b981" },
  sentry: { icon: SiSentry, color: "#362D59" },

  // Databases
  postgresql: { icon: SiPostgresql, color: "#4169E1" },
  mysql: { icon: SiMysql, color: "#4479A1" },
  redis: { icon: SiRedis, color: "#DC382D" },
  mongodb: { icon: SiMongodb, color: "#47A248" },
  elasticsearch: { icon: SiElasticsearch, color: "#005571" },
  sqlite: { icon: SiSqlite, color: "#003B57" },
  supabase: { icon: SiSupabase, color: "#3FCF8E" },
  firebase: { icon: SiFirebase, color: "#FFCA28" },
  prisma: { icon: SiPrisma, color: "#2D3748" },
  drizzle: { icon: SiDrizzle, color: "#C5F74F" },
  rabbitmq: { icon: SiRabbitmq, color: "#FF6600" },
  kafka: { icon: SiApachekafka, color: "#231F20" },

  // Tools & Testing
  git: { icon: SiGit, color: "#F05032" },
  linux: { icon: SiLinux, color: "#FCC624" },
  vim: { icon: SiVim, color: "#019733" },
  neovim: { icon: SiNeovim, color: "#57A143" },
  figma: { icon: SiFigma, color: "#F24E1E" },
  webpack: { icon: SiWebpack, color: "#8DD6F9" },
  vite: { icon: SiVite, color: "#646CFF" },
  jest: { icon: SiJest, color: "#C21325" },
  vitest: { icon: SiVitest, color: "#6E9F18" },
  cypress: { icon: SiCypress, color: "#69D3A7" },
  playwright: { icon: TbTestPipe2, color: "#2EAD33" },
  storybook: { icon: SiStorybook, color: "#FF4785" },
  testinglibrary: { icon: SiTestinglibrary, color: "#E33332" },
  bash: { icon: SiGnubash, color: "#4EAA25" },
  zod: { icon: SiZod, color: "#3E67B1" },
  npm: { icon: SiNpm, color: "#CB3837" },
  pnpm: { icon: SiPnpm, color: "#F69220" },
  yarn: { icon: SiYarn, color: "#2C8EBB" },
  postman: { icon: SiPostman, color: "#FF6C37" },
  swagger: { icon: SiSwagger, color: "#85EA2D" },
  stripe: { icon: SiStripe, color: "#635BFF" },
  auth0: { icon: SiAuth0, color: "#EB5424" },
  jwt: { icon: SiJsonwebtokens, color: "#ffffff" },
  electron: { icon: SiElectron, color: "#47848F" },
  tauri: { icon: SiTauri, color: "#FFC131" },
  reactnative: { icon: SiReactos, color: "#61DAFB" },
  flutter: { icon: SiFlutter, color: "#02569B" },
  dart: { icon: SiDart, color: "#0175C2" },
  solidity: { icon: SiSolidity, color: "#363636" },
  reactquery: { icon: SiReactquery, color: "#FF4154" },
  redux: { icon: SiRedux, color: "#764ABC" },
  markdown: { icon: SiMarkdown, color: "#ffffff" },
  notion: { icon: SiNotion, color: "#ffffff" },
  jira: { icon: SiJira, color: "#0052CC" },
  slack: { icon: SiSlack, color: "#4A154B" },
  openai: { icon: SiOpenai, color: "#412991" },
}

/** All available icon names for the admin picker */
export const availableIconNames = Object.keys(techIcons).sort()

/** Lookup helper — returns icon + color, or null if not found */
export function getTechIcon(iconName: string | null | undefined): TechIcon | null {
  if (!iconName) return null
  return techIcons[iconName.toLowerCase()] ?? null
}
